CREATE DATABASE fiap;

USE fiap;

DROP TABLE users;
CREATE TABLE `fiap`.`users` (
`Id` INT NOT NULL AUTO_INCREMENT,
`Name` VARCHAR(45) NULL,
`Email` VARCHAR(45) NULL,
PRIMARY KEY (`Id`));

SELECT * FROM users;