CREATE DATABASE fiap;

USE fiap;

DROP TABLE users;
CREATE TABLE `fiap`.`users` (
`Id` INT NOT NULL AUTO_INCREMENT,
`Name` VARCHAR(45) NULL,
`Email` VARCHAR(45) NULL,
PRIMARY KEY (`Id`));

SELECT * FROM users;

DROP TABLE vehicles;
CREATE TABLE `fiap`.`vehicles` (
`Id` INT NOT NULL AUTO_INCREMENT,
`Brand` VARCHAR(45) NOT NULL,
`Model` VARCHAR(45) NOT NULL,
`Year` INT NOT NULL,
`Plate` VARCHAR(45) NOT NULL UNIQUE,
PRIMARY KEY (`Id`));

SELECT * FROM vehicles;